[package]
name = "muli"
version = "0.1.0"
authors = ["Theo Breuer-Weil <theo.breuer-weil@cazoo.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
